/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHome {}
  interface TodoWidget {
    'todoListData': any;
  }
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLTodoWidgetElement extends Components.TodoWidget, HTMLStencilElement {}
  var HTMLTodoWidgetElement: {
    prototype: HTMLTodoWidgetElement;
    new (): HTMLTodoWidgetElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'todo-widget': HTMLTodoWidgetElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {}
  interface TodoWidget {
    'todoListData'?: any;
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'todo-widget': TodoWidget;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'todo-widget': LocalJSX.TodoWidget & JSXBase.HTMLAttributes<HTMLTodoWidgetElement>;
    }
  }
}


